# Page settings
baseurl = "http://maddyking44.com"
title = "Welcome to the Wizzness"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Maddy King"
  description = "Success Strategy for Solopreneurs"
  email = "me@maddyking44.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = "AIzaSyD8LUGgQL_3fELUvXyeZPK90xO9hY6ppLs"

  # Navigation
  [params.navigation]
    brand = "GSD"
    home = "Home"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    work = "Work"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Launch Yourself"
    subtitle = 'Success Strategy for Solopreneurs'
 
  # Intro section
  # Available icons: https://simplelineicons.github.io/
  [params.intro]

  [[params.intro.item]]
    title = "Understand"
    description = "Gain insights to learn what makes your customers tick."
    url = "#fh5co-contact"
    button = "Get in touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Craft your product to generate sales."
    url = "#fh5co-contact"
    button = "Book now"
    icon = "icon-energy"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Smash goals and measure results."
    url = "#fh5co-contact"
    button = "Learn more"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "How it's done"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=mKQXLfkU3yA"
    subheading = "Working with The Realness" 


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "It's fun when we work together."

    [[params.testimonials.item]]
      quote = "&ldquo;Testimony pending. &rdquo;"
      person = 'Josh Gunn, Tech Lead - <a href="http://swayable.com" target="_blank">Swayable</a>'
      img = "S.png"
      alt = "Digital marketing coach"

    [[params.testimonials.item]]
      quote = "&ldquo;Testimony pending. &rdquo;"
      person = 'Damaris Coulter, CEO - <a href="http://therealness.world/" target="_blank">The Realness</a>'
      img = "R.png"
      alt = "Launch strategy"

    [[params.testimonials.item]]
      quote = "&ldquo;Testimony pending. &rdquo;"
      person = 'Rohan Jarvis, Director - <a href="http://freehtml5.co/" target="_blank">LALATAT</a> <span class="subtext"></span>'
      img = "L.png"
      alt = "Business advice"
    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Boosting your business from end to end."

    [[params.services.item]]
      title = "Market Insights"
      description = "Let's start by understanding your purpose, from a product perspective, and your value proposition from your customer's perspective. What brings them to your door?"
      icon = "icon-fire"

    [[params.services.item]]
      title = "Product Development"
      description = "We can refine your product to exclusively focus on things that are going to excite your customer, rather than extra features. This saves time and money in the long run, and builds a product you're proud of."
      icon = "icon-pencil"
    [[params.services.item]]
      title = "Digital Consultancy"
      description = "Your messaging to the world comes through yoru digital portals. We can identify barriers and streamline your digital presence to generate sales."
      icon = "icon-chart"

      [[params.services.item]]
      title = "Marketing Strategy"
      description = "A deep understanding of the product and market means we can put your business in front of the people that matter, efficiently and effectively reaching your customers."      
      icon = "icon-bubble"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Maddy King has been working with startups across the spectrum of business activities."

    [[params.about.item]]
      name = "Communication"
      position = "The secret sauce of empathy"
      description = "Marketing experience lets me put myself in the shoes of your customer, and understand their needs."
      img = "maddyKing_3.png"
      alt = "Maddy King communications expert"
      social = [
        ["icon-cup"],
        ["icon-bubbles"],
        ["icon-share"]
      ]

    [[params.about.item]]
      name = "Business Insights"
      position = "How do we make this sustainable?"
      description = "My passion for data-driven decisionmaking means we can save money while generating better results."
      img = "maddyKing_1.jpg"
      alt = "Maddy King business insights for entrepreneurs"
      social = [
        ["icon-pin"],
        ["icon-graph"],
        ["icon-puzzle"]
      ]

    [[params.about.item]]
      name = "Technical skills"
      position = "Speaks tech"
      description = "Sometimes you need an experienced coder to help make technical decisions and get the most out of your developers."
      img = "maddyKing_2.png"
      alt = "Digital project manager"
      social = [
        ["icon-link"],
        ["icon-speedometer"],
        ["icon-mouse"]
      ]      


# Work section
  [params.work]
    enable = true
    title = "Work"
    description = "These projects are now singing"
    footertext = ''

    [[params.work.row]]
      img = "lalatat.svg"
      alt = "Image4"
      title = "LALATAT"
      subtitle = "Marketing and Launch consulatancy"
      style = "object-fit: fill"

    [[params.work.row]]
      img = "realness.png"
      alt = "Image2"
      title = "The Realness"
      subtitle = "Product Management"

    [[params.work.row]]
      img = "swayable.jpg"
      alt = "Image2"
      title = "Swayable"
      subtitle = "Web Development"

    [[params.work.row]]
      img = "clicksuite.jpg"
      alt = "Image3"
      title = "Clicksuite"
      subtitle = "Game development for Te Papa"

    [[params.work.row]]
      img = "don_eda.jpg"
      alt = "Image5"
      title = "Enspiral Dev Academy"
      subtitle = "Marketing Management"

    [[params.work.row]]
      img = "beyondviolence.jpg"
      alt = "Image6"
      title = "Beyond Violence"
      subtitle = "Campaign Management"
      style = "object-fit: contain"


# Case Study section
  [params.casestudy]
    enable = true
    title = "Case Study"
    description = "Working with The Realness"
    icon= "icon-energy"




  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 20
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of tea"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 9
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Let's get a coffee (or an online cup of tea), talk about your vision and see if I can help."
    
    # Available icons: https://simplelineicons.github.io/
    details = [
        ["icon-home", "Level 2, 40 Taranaki Street, Wellington"],
        ["icon-globe", "Success working with clients remotely"],
        ["icon-envelope", "me@maddyking44.com"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Configure map address in hugo-elate-theme/ static/ js/ leaflet-map.js var latLong

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Maddy King 2020'
    links = [
        ["icon-twitter", "http://www.twitter.com/maddyking44"],
        ["icon-facebook", "http://www.facebook.com/maddy.king.71"],
        ["icon-linkedin", "http://www.linkedin.com/in/madelineking44"]
      ]
