# Page settings
baseurl = "http://maddyking44.com"
title = "Maddy King - Business Success Support"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Maddy King"
  description = "Success Strategy for Solopreneurs"
  email = "me@maddyking44.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = "AIzaSyD8LUGgQL_3fELUvXyeZPK90xO9hY6ppLs"

  # Navigation
  [params.navigation]
    brand = "HI! I'M MADDY"
    home = "Home"
    products = "Products"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    work = "Work"
    casestudy = "Casestudy"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Launch Yourself"
    subtitle = 'Success Strategy for Solopreneurs'
 
  # Intro section
  # Available icons: https://simplelineicons.github.io/
  [params.intro]

  [[params.intro.item]]
    title = "Understand"
    description = "Gain insights to learn what makes your customers tick."
    url = "#fh5co-contact"
    button = "Get in touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "Craft your product to generate sales."
    url = "#fh5co-contact"
    button = "Book now"
    icon = "icon-energy"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Smash goals and measure results."
    url = "#fh5co-contact"
    button = "Learn more"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Hi! I'm Maddy. Nice to meet you."
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=VmuUbXOsbAM"
    subheading = "" 

# Products section
  [params.products]
    enable = true
    title = "Products"
    description = "A couple of ways we can help your business"
    footertext = ''
    url = "#fh5co-testimonials"
    button = "Hear from customers"

    [[params.products.row]]
      img = "analyticstool.jpg"
      alt = "Analytics insights free tool"
      icon="icon-magnifier"
      title = "Analytics Analyzer"
      subtitle = "A neat little tool I built to help you gain useful insights from your Google Analytics data."
      cost = "Free"

    [[params.products.row]]
      img = "marketingmanager.jpg"
      alt = "Become your own marketing manager workshop"
      icon = "icon-speedometer"
      title = "Become your own Marketing Manager workshops"
      subtitle = "A 5 week series of one-on-one digital marketing strategy workshops that cover customer discovery, social media channel selection and best practice, customer engagement strategy and data analytics to spend the least amount for the greatest results."
      cost = "$500"

    [[params.products.row]]
      img = "webpage2.jpg"
      alt = "One day webpage"
      icon="icon-screen-desktop"
      title = "One day Webpage"
      subtitle = "A basic marketing website (like this one), built from a template and put online in one day."
      cost = "$800"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "It's fun when we work together."

    [[params.testimonials.item]]
      quote = "&ldquo;Communication was easy and she was a pleasure to work with. We were particularly impressed by Maddy’s ability to transform loose specifications into production ready features. &rdquo;"
      person = 'Josh Gunn, Lead Sorftware Engineer - <a href="https://swayable.com" target="_blank" rel="noopener noreferrer">Swayable</a>'
      img = "josh.jpg"
      alt = "Digital marketing coach"

    [[params.testimonials.item]]
      quote = "&ldquo;Maddy helped the Realness by identifying problems that we were couldn’t quite put our finger on, or know how to articulate. She was the bridge between us and the developers. Since Maddy came on board I feel confident and proud of my platform. Working with her has been a dream. She exceeded my expectations, which was delightful, because many had underdelivered over the last few years. Her work ethic was unquestionable and I always felt like she went above and beyond for us. She is straight up, efficient and conscientious, and best of all she’s a problem solver not a problem moaner. I'd recommend Maddy to anyone who needs a project manager, an all-rounder, a brainstormer, a development advisor, a developer, an everything-er.&rdquo;"
      person = 'Damaris Coulter, CEO - <a href="https://therealness.world/" target="_blank" rel="noopener noreferrer">The Realness</a> <span class="subtext"></span>'
      img = "damaris.jpg"
      alt = "Small business support"

    [[params.testimonials.item]]
      quote = "&ldquo;The Digital Marketing course that Maddy delivers is an excellent way to develop and implement a Social Media Marketing strategy. It was a great balance between instructional content and making you think outside of the box! Easy to follow, knowledgeable and challenged the thinking of the attendees. &rdquo;"
      person = 'Rohan Jarvis, Director - <a href="https://lalatat.com/" target="_blank"  rel="noopener noreferrer">LALATAT</a> <span class="subtext"></span>'
      img = "rohan.jpg"
      alt = "Business advice"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Boosting your business from end to end."

    [[params.services.item]]
      title = "Customer Insights"
      description = "Let's start by understanding your product's purpose and value proposition from your customer's perspective. What brings them to your door?"
      icon = "icon-fire"

    [[params.services.item]]
      title = "Product Development"
      description = "We can refine your product to exclusively focus on things that are going to excite your customer, rather than extra features. This saves time and money, and builds a product you're proud of."
      icon = "icon-pencil"
    [[params.services.item]]
      title = "Digital Enablement"
      description = "Your messaging to the world comes through your digital portals. We can identify barriers and streamline your digital presence to generate sales."
      icon = "icon-share"

      [[params.services.item]]
      title = "Marketing Strategy"
      description = "A deep understanding of the product and market means we can put your business in front of the people that matter, efficiently and effectively reaching your customers."      
      icon = "icon-bubble"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "I've been working with small businesses across the spectrum of business activities."
    url = "#fh5co-contact"
    button = "Get in touch now"

    [[params.about.item]]
      name = "Communication"
      position = "The secret sauce of empathy"
      description = "Marketing experience lets me put myself in the shoes of your customer, and understand their needs."
      img = "maddyKing_3.png"
      alt = "Maddy King communications expert"
      social = [
        ["icon-cup"],
        ["icon-bubbles"],
        ["icon-share"]
      ]

    [[params.about.item]]
      name = "Business Insights"
      position = "How do we make this sustainable?"
      description = "My passion for data-driven decisionmaking means we can save money while generating better results."
      img = "maddyKing_1.jpg"
      alt = "Maddy King business insights for entrepreneurs"
      social = [
        ["icon-pin"],
        ["icon-graph"],
        ["icon-puzzle"]
      ]

    [[params.about.item]]
      name = "Technical skills"
      position = "Speaks tech"
      description = "Sometimes you need an experienced coder to help make technical decisions and get the most out of your developers."
      img = "maddyKing_2.png"
      alt = "Digital project manager"
      social = [
        ["icon-link"],
        ["icon-speedometer"],
        ["icon-mouse"]
      ]      

# Work section
  [params.work]
    enable = true
    title = "Previous Work"
    description = "These projects are now singing"
    footertext = ''
    url = "#fh5co-contact"
    button = "Book now"

    [[params.work.row]]
      img = "lalatat.svg"
      alt = "digital strategy"
      url= "https://lalatat.com"
      title = "LALATAT"
      subtitle = "Marketing and Launch consulatancy"
      style = "object-fit: fill"

    [[params.work.row]]
      img = "realness.png"
      alt = "small business consultant"
      url= "https://therealness.world"
      title = "The Realness"
      subtitle = "Product Management"

    [[params.work.row]]
      img = "swayable.jpg"
      alt = "marketing consultant"
      url= "https://swayable.com"
      title = "Swayable"
      subtitle = "Web Development"

    [[params.work.row]]
      img = "webpage.jpg"
      alt = "digital project manager"
      url= "https://www.bamboocreative.nz/"
      title = "Bamboo Creative"
      subtitle = "Web Development"

    [[params.work.row]]
      img = "don_eda.jpg"
      alt = "low cost social media marketing"
      url= "https://devacademy.co.nz/"
      title = "Enspiral Dev Academy"
      subtitle = "Marketing Management"

    [[params.work.row]]
      img = "beyondviolence.jpg"
      alt = "campaign manager"
      url= "https://www.youtube.com/watch?v=HIwTJVXNOH4"
      title = "Beyond Violence"
      subtitle = "Campaign Management"
      style = "object-fit: contain"

# Casestudy section
  [params.casestudy]
    enable = false
    title = "Case Study"
    description = "Working with The Realness"
    icon= ""

    [params.casestudy.video]
      enable = true
      title = ""
      icon = "icon-energy"
      url = "https://www.youtube.com/watch?v=8HvPHo8Ldc0"
      subheading = "Working with The Realness" 


  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 20
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Cups of tea"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 9
      interval = 50
      speed = 4000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Let's get a coffee (or an online cup of tea), talk about your vision and see if I can help."
    
    # Available icons: https://simplelineicons.github.io/
    details = [
        ["icon-home", "Level 2, 40 Taranaki Street, Wellington"],
        ["icon-globe", "Success working with clients remotely"],
        ["icon-envelope", "me@maddyking44.com"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Configure map address in hugo-elate-theme/ static/ js/ leaflet-map.js var latLong

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Maddy King 2020'
    links = [
        ["icon-twitter", "http://www.twitter.com/maddyking44"],
        ["icon-facebook", "http://www.facebook.com/maddy.king.71"],
        ["icon-linkedin", "http://www.linkedin.com/in/madelineking44"]
      ]
