# Page settings
baseurl = "http://maddyking44.com"
title = "Maddy King in a world"
languageCode = "en-us"
theme = "hugo-elate-theme"
googleAnalytics = "UA-173142204-1"

[params]

  # Meta
  author = "Maddy King"
  description = "Creative digital art and experimenting with different realities through 3D interactive web experiences, games and VR / AR / XR "
  email = "me@maddyking44.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = "AIzaSyD8LUGgQL_3fELUvXyeZPK90xO9hY6ppLs"

  # Navigation
  [params.navigation]
    icon = "icon-rocket"
    home = "Home"
    introAbout = "About"
    about = "Quote"
    work = "Portfolio"
    testimonials = "Testimonies"
    products = "Playground"
    productsweb = "Web"
    productsTwo = "Storytelling"
    services = "Freebie"

    casestudy = "Casestudy"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Maddy King"
    subtitle = ['Hack','Experiment','Create']
 
  # Intro section
  # Available icons: https://simplelineicons.github.io/
  [params.intro]
    enable=true

  [[params.intro.item]]
    title = "Portfolio"
    description = "A smattering of past projects"
    url = "#fh5co-work"
    button = "Show me"
    icon = "icon-people"
    img = "clients/img_7.jpg"
    trackingCode = "social"

  [[params.intro.item]]
    title = "Testimonies"
    description = "Some nice words about my work"
    url = "#fh5co-testimonials"
    button = "Lovely"
    icon = "icon-fire"
    img = "clients/img_10.jpg"
    trackingCode = "business"

  [[params.intro.item]]
    title = "Playground"
    description = "Experiments in progress"
    url = "#fh5co-products"
    button = "Sounds weird"
    icon = "icon-energy"
    img = "clients/img_8.jpg"
    trackingCode = "web"

  [params.intro.quote]
    enable=true
    text1="lecturer in VR and AR for creative expression (and to change the world)"
    text2="Massey University, Wellington"
    text3="make creative digital art and experiment with different realities"
    text4="3D interactive web experiences, games, VR / AR / XR"
    text5="very interested in using technology education to dismantle oppressive power structures"
    name=""
    img = "MaddyKingDigital.jpg"

  [params.intro.video]
    enable = false 
    title = "Time to level up your business?"
    subheading = ""
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=OKKbtq1JlTY"


# Products section
  [params.products]
    enable = true
    title = "My playground"
    description = "The place where I experiment with new ideas and break things. Usually in the realm of AR (augmented reality), VR (virtual reality), WebXR (immersive worldbuilding online), three.js and other tools for creating immersive visual experiences."
    footertext = ''
    icon = "icon-wrench"
    url = "https://bsides44.github.io"
    button = "Take me there"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonies"
    description = "People are wonderful."

    [[params.testimonials.item]]
      quote = "&ldquo;Communication was easy and she was a pleasure to work with. We were particularly impressed by Maddy’s ability to transform loose specifications into production ready features.&rdquo;"
      person = 'Josh Gunn, Tech Lead - <a href="https://swayable.com" target="_blank" rel="noopener noreferrer">Swayable</a>'
      img = "clients/josh.jpg"
      alt = "Digital marketing coach Wellington"

    [[params.testimonials.item]]
      quote = "&ldquo;Maddy was the bridge between us and the developers - us and a world we did not understand. Working with her has been a dream. She exceeded my expectations, which was delightful, because many had underdelivered before. Her work ethic was unquestionable and I always felt like she went above and beyond for us. She is straight up, efficient and conscientious, and best of all she’s a problem solver not a problem moaner. I'd recommend Maddy to anyone who needs a project manager, an all-rounder, a brainstormer, a development advisor, a developer, an everything-er.&rdquo;"
      person = 'Damaris Coulter, CEO - <a href="https://therealness.world/" target="_blank" rel="noopener noreferrer">The Realness</a> <span class="subtext"></span>'
      img = "clients/damaris.jpg"
      alt = "Small business support Wellington"

    [[params.testimonials.item]]
      quote = "&ldquo;The Digital Marketing course that Maddy delivers is an excellent way to develop and implement a Social Media Marketing strategy. It was a great balance between instructional content and making you think outside of the box! Easy to follow, knowledgeable and challenged the thinking of the attendees.&rdquo;"
      person = 'Rohan Jarvis, Director - <a href="https://lalatat.com/" target="_blank"  rel="noopener noreferrer">LALATAT</a> <span class="subtext"></span>'
      img = "clients/rohan.jpg"
      alt = "Business advice Wellington"

# Web Products section
  [params.productsweb]
    enable = false
    title = "Website and App Support"
    description = "Presenting your brand proudly to the world and solving your digital challenges."
    footertext = ''
    url = "#fh5co-contact"
    button = "Get in touch now"

    [[params.productsweb.rowOne]]
      img = "facebookadvertising.jpg"
      alt = "one page website new zealand"
      icon="icon-magnifier"
      title = "One Page Website"
      subtitle = "A stunning website that speaks directly to your customer and drives them to buy. Built with SEO to improve your chances on Google. Comes with Google Analytics installed so you can constantly improve your results. I'll also show you a simple way to update your site yourself, so you're in charge."
      cost = "$1000"
      trackingCode = "one-page-website"

    [[params.productsweb.rowOne]]
      img = "webdevelopment.jpg"
      alt = "digital project manager"
      icon = "icon-speedometer"
      title = "Technical Project Manager"
      subtitle = "Got a digital project that feels difficult and complicated? I can come in, help you determine a functional, cost-effective solution, and liaise with your developers to ensure you're getting value for money. I'll help you set up your systems, understand technical decisions and carry out your work on time and on buget, so you end up with a project you're proud of."
      cost = "Project specific"
      trackingCode = "project-manager"

    [[params.productsweb.rowOne]]
      img = "improvewebapp.jpg"
      alt = "Product support"
      icon="icon-magnifier"
      title = "Product Direction"
      subtitle = "Feel like your product isn't quite living up to its potential? By understanding your customers, your value proposition and your business model, I can help you make product decisions that generate revenue and grow your user base of happy, vocal clients."
      cost = "Project specific"
      trackingCode = "product-direction"

    [[params.productsweb.rowTwo]]
      img = "analyticstool.jpg"
      alt = "Web development"
      icon="icon-magnifier"
      title = "Web Development"
      subtitle = "Building or improving your web application. As a full stack web developer across a range of technologies I can craft a product or platform for you that is easy, cost-effective and intuitive for the user."
      cost = "Project specific"
      trackingCode = "product-direction"

# ProductsTwo section
  [params.productsTwo]
    enable = true
    title = "The Two Dimensional Storyteller"
    description = "Traditional linear storylines have one dimension: they go in a line, from beginning, to middle, to end. This worked well for books and movies, because you experience the plot in a set order. But as we move into a world of mixed, multimedia, interactive and immersive storytelling, we need greater breadth to our storywriting. Introducing the Two-Dimensional Storyteller - a tool to help you write a story that can go in many directions."
    footertext = ''
    icon = "icon-compass"
    url = "https://storyteller.maddyking44.com"
    button = "Show me how"

  # Services section
  [params.services]
    enable = true
    title = "Free Google Analytics Tool"
    description = "An easy cheatsheet to boost your search performance."
    url = "https://analytics.maddyking44.com"
    button = "Yes Please"

    [[params.services.item]]
      title = "Learn more about your customers"
      description = ""
      icon = "icon-fire"

    [[params.services.item]]
      title = "See which parts of your product they're drawn to"
      description = ""
      icon = "icon-puzzle"
    [[params.services.item]]
      title = "Learn tricks to optimise your website for more views and sales"
      description = ""
      icon = "icon-trophy"

      [[params.services.item]]
      title = "Make your digital business more successful"
      description = ""      
      icon = "icon-energy"

  # About section
  [params.about]
    enable = true
    title = ""
    icon= "icon-bulb"
    description="&ldquo;Maddy helped us by identifying problems that we couldn’t quite put our finger on, or know how to articulate - and then working to solve those problems. Since Maddy came on board I feel confident in and proud of my platform.&rdquo;"
    name="Damaris Coulter, CEO <a href='http://www.therealness.world' target='_blank' rel='noopener noreferrer' style='text-decoration: underline'>The Realness</a>"
    img = "MaddyKingDigital.jpg"

# Work section
  [params.work]
    enable = true
    title = "Previous Work"
    description = "Some excellent organisations that I've helped in different ways"
    footertext = ''
    url = "#fh5co-contact"
    button = "Get in touch"

    [[params.work.row]]
      img = "clients/lalatat.svg"
      alt = "digital strategy"
      url= "https://lalatat.com"
      title = "LALATAT"
      subtitle = "Marketing Training"
      style = "object-fit: fill"
      trackingCode = "lalatat"

    [[params.work.row]]
      img = "clients/realness.png"
      alt = "small business consultant"
      url= "https://therealness.world"
      title = "The Realness"
      subtitle = "Product Management"
      trackingCode = "the-realness"

    [[params.work.row]]
      img = "clients/swayable.jpg"
      alt = "marketing consultant"
      url= "https://swayable.com"
      title = "Swayable"
      subtitle = "Web Development"
      trackingCode = "swayable"

    [[params.work.row]]
      img = "clients/bamboocreative.svg"
      alt = "digital project manager"
      url= "https://bamboocreative.nz/"
      title = "Bamboo Creative"
      subtitle = "Web Development"
      style = "object-fit: contain"
      trackingCode = "bamboo"

    [[params.work.row]]
      img = "clients/don_eda.jpg"
      alt = "low cost social media marketing"
      url= "https://devacademy.co.nz/"
      title = "Enspiral Dev Academy"
      subtitle = "Marketing Management"
      trackingCode = "dev-academy"

    [[params.work.row]]
      img = "clients/beyondviolence.jpg"
      alt = "campaign manager"
      url= "https://www.youtube.com/watch?v=HIwTJVXNOH4"
      title = "Beyond Violence"
      subtitle = "Project Management"
      style = "object-fit: contain"
      trackingCode = "beyond-violence"

# Casestudy section
  [params.casestudy]
    enable = false
    title = "Case Study"
    description = "Working with The Realness"
    icon= ""

    [params.casestudy.video]
      enable = true
      title = ""
      icon = "icon-energy"
      url = "https://www.youtube.com/watch?v=8HvPHo8Ldc0"
      subheading = "Working with The Realness" 


  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "clients/full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 40
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Cups of tea"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 15
      interval = 50
      speed = 4000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Let's get a coffee and talk about the last thing you broke"
    
    # Available icons: https://simplelineicons.github.io/
    details = [
        ["icon-home", "Currently based at Massey, Wellington"],
        ["icon-globe", "I like working remotely"],
        ["icon-envelope", "me@maddyking44.com"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Configure map address in hugo-elate-theme/ static/ js/ leaflet-map.js var latLong

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Maddy King 2021'
    links = [
        ["icon-twitter", "http://www.twitter.com/maddyking44"],
        ["icon-facebook", "http://www.facebook.com/maddy.king.71"],
        ["icon-linkedin", "http://www.linkedin.com/in/madelineking44"]
      ]
