# Page settings
baseurl = "http://maddyking44.com"
title = "Maddy King - Success and Strategy for Small Businesses"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Maddy King"
  description = "Success and Strategy for Small Businesses"
  email = "me@maddyking44.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = "AIzaSyD8LUGgQL_3fELUvXyeZPK90xO9hY6ppLs"

  # Navigation
  [params.navigation]
    icon = "icon-rocket"
    home = "Home"
    products = "Social Media"
    testimonials = "Testimonials"
    productsweb = "Web"
    services = "Services"
    about = "About"
    work = "Work"
    casestudy = "Casestudy"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Maddy King"
    subtitle = 'Success and Strategy for Small Businesses'
 
  # Intro section
  # Available icons: https://simplelineicons.github.io/
  [params.intro]

  [[params.intro.item]]
    title = "Help me with social media"
    description = "Build your community of customers"
    url = "#fh5co-products"
    button = "Boost my brand"
    icon = "icon-people"
    img = "clients/img_7.jpg"

  [[params.intro.item]]
    title = "Help me with my website"
    description = "Get your brand in front of people who want to buy it"
    url = "#fh5co-productsweb"
    button = "Amplify my website"
    icon = "icon-energy"
    img = "clients/img_8.jpg"

  [[params.intro.item]]
    title = "Help me with everything"
    description = "Get support to generate more sales for your business"
    url = "#fh5co-testimonials"
    button = "Learn more"
    icon = "icon-fire"
    img = "clients/img_10.jpg"

  [params.intro.quote]
    enable=true
    text="&ldquo;Maddy helped our business by identifying problems that we couldn’t quite put our finger on, or know how to articulate - and then working to solve those problems. Since Maddy came on board I feel confident in and proud of my platform.&rdquo;"
    name="Damaris Coulter, CEO"

  [params.intro.video]
    enable = false 
    title = "Time to level up your business?"
    subheading = ""
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=OKKbtq1JlTY"


# Products section
  [params.products]
    enable = true
    title = "Social Media Support"
    description = "Using digital tools to grab your customers' attention for less."
    footertext = ''
    url = "#fh5co-testimonials"
    button = "Hear from happy clients"

    [[params.products.rowOne]]
      img = "marketingmanager.jpg"
      alt = "Social media marketing workshop"
      icon="icon-magnifier"
      title = "Social Media Strategy workshop"
      subtitle = "Save money in the long run by working with me to build a winning social media strategy. We'll dive into your potential customers, figure out where to attract them online and make a plan to engage their interest and bring in those sales."
      cost = "$250"

    [[params.products.rowOne]]
      img = "adstraining.jpg"
      alt = "Google ads training"
      icon = "icon-speedometer"
      title = "Digital Marketing Training"
      subtitle = "Learn more about how to establish your strategy yourself. Understand how to target your customer, inspire their curiosity and lead them to your product. You'll learn best practice tips, and how to use data analytics to track the results of your posts, see what's working and improve what isn't. This strategy means you won't waste money on work that isn't leading to sales."
      cost = "$750"

    [[params.products.rowOne]]
      img = "googleadwords.jpg"
      alt = "Digital Ads Training"
      icon="icon-magnifier"
      title = "Digital Ads Training"
      subtitle = "Learn how to get the most out of your Instagram ads, Facebook ads and Google Adwords. We'll run through building audiences and setting up ads to generate the best results for the lowest cost, increasing your business reach, accessing more customers and making more sales."
      cost = "$500"

    [[params.products.rowTwo]]
      img = "webpage.jpg"
      alt = "Google Analytics free tool"
      icon="icon-magnifier"
      title = "Google Analytics Tool"
      subtitle = "A free tool to help you gain insights from your Google Analytics data. Learn more about your customers, reach more people with your digital advertising for less cost, and improve sales from your website."
      cost = "Free"

    [[params.products.rowTwo]]
      img = "facebookadvertising.jpg"
      alt = "Google Analytics Insights"
      icon="icon-magnifier"
      title = "Google Analytics insights"
      subtitle = "Generating growth through data as a service. I'll analyse your Google Analytics to determine how to grow your business."
      cost = "$250"

    [[params.products.rowTwo]]
      img = "socialmediaworkshop.jpg"
      alt = "Set up social media channels"
      icon="icon-magnifier"
      title = "Set up Social Channels"
      subtitle = "I can set up your social media accounts for you with recurring ads to present your brand to your customers and reach the right audiences."
      cost = "$250"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "It's fun when we work together."

    [[params.testimonials.item]]
      quote = "&ldquo;Communication was easy and she was a pleasure to work with. We were particularly impressed by Maddy’s ability to transform loose specifications into production ready features.&rdquo;"
      person = 'Josh Gunn, Tech Lead - <a href="https://swayable.com" target="_blank" rel="noopener noreferrer">Swayable</a>'
      img = "clients/josh.jpg"
      alt = "Digital marketing coach"

    [[params.testimonials.item]]
      quote = "&ldquo;Maddy was the bridge between us and the developers - us and a world we did not understand. Working with her has been a dream. She exceeded my expectations, which was delightful, because many had underdelivered before. Her work ethic was unquestionable and I always felt like she went above and beyond for us. She is straight up, efficient and conscientious, and best of all she’s a problem solver not a problem moaner. I'd recommend Maddy to anyone who needs a project manager, an all-rounder, a brainstormer, a development advisor, a developer, an everything-er.&rdquo;"
      person = 'Damaris Coulter, CEO - <a href="https://therealness.world/" target="_blank" rel="noopener noreferrer">The Realness</a> <span class="subtext"></span>'
      img = "clients/damaris.jpg"
      alt = "Small business support"

    [[params.testimonials.item]]
      quote = "&ldquo;The Digital Marketing course that Maddy delivers is an excellent way to develop and implement a Social Media Marketing strategy. It was a great balance between instructional content and making you think outside of the box! Easy to follow, knowledgeable and challenged the thinking of the attendees.&rdquo;"
      person = 'Rohan Jarvis, Director - <a href="https://lalatat.com/" target="_blank"  rel="noopener noreferrer">LALATAT</a> <span class="subtext"></span>'
      img = "clients/rohan.jpg"
      alt = "Business advice"

# Web Products section
  [params.productsweb]
    enable = true
    title = "Website and App Support"
    description = "Presenting your brand proudly to the world and solving your digital challenges."
    footertext = ''
    url = "#fh5co-testimonials"
    button = "Get in touch now"

    [[params.productsweb.rowOne]]
      img = "instagramads.jpg"
      alt = "one page website"
      icon="icon-magnifier"
      title = "One Page Website"
      subtitle = "A stunning website that speaks directly to your customer and drives them to buy. Built with SEO to improve your chances on Google. Comes with Google Analytics installed so you can constantly improve your results. I'll also show you a simple way to update your site yourself, so you're in charge."
      cost = "$1000"

    [[params.productsweb.rowOne]]
      img = "analyticstool.jpg"
      alt = "digital project manager"
      icon = "icon-speedometer"
      title = "Digital Project Manager"
      subtitle = "Got a digital project that feels difficult and complicated? I can come in, help you determine a functional, cost-effective solution, and liaise with your developers to ensure you're getting value for money. I'll help set up your systems and give you clear, straightforward explanations of technical decisions, so you end up with a project you're proud of."
      cost = "Project specific"

    [[params.productsweb.rowOne]]
      img = "website.jpg"
      alt = "Product support"
      icon="icon-magnifier"
      title = "Product Direction"
      subtitle = "Feel like your product isn't quite living up to its potential? By understanding your customers, your value proposition and your business model, I can help you make product decisions that generate revenue and grow your user base of happy, vocal clients."
      cost = "Project specific"

  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Boosting your business from end to end."

    [[params.services.item]]
      title = "Customer Insights"
      description = "Let's start by understanding your product's purpose and value proposition from your customer's perspective. What brings them to your door?"
      icon = "icon-fire"

    [[params.services.item]]
      title = "Product Development"
      description = "We can refine your product to exclusively focus on things that are going to excite your customer, rather than extra features. This saves time and money, and builds a product you're proud of."
      icon = "icon-pencil"
    [[params.services.item]]
      title = "Digital Enablement"
      description = "Your messaging to the world comes through your digital portals. We can identify barriers and streamline your digital presence to generate sales."
      icon = "icon-share"

      [[params.services.item]]
      title = "Marketing Strategy"
      description = "A deep understanding of the product and market means we can put your business in front of the people that matter, efficiently and effectively reaching your customers."      
      icon = "icon-bubble"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "I work fanatically to boost great business ideas using digital tools."
    url = "#fh5co-contact"
    button = "Get in touch now"

    [[params.about.item]]
      name = "Communication"
      position = "Understanding your customer"
      description = "With 10 years digital marketing experience, I can help you understand your ideal customers and the fundamental motivations leading them to your product. This insight allows us to carefully target segments of the market that are likely to buy your product, and craft messaging that speaks to directly to their core experiences."
      img = "maddyKing_3.jpg"
      alt = "Maddy King communications expert"
      social = [
        ["icon-cup"],
        ["icon-bubbles"],
        ["icon-share"]
      ]

    [[params.about.item]]
      name = "Business Insights"
      position = "How do we make this sustainable?"
      description = "Today's digital tools allow us to get under the skin of your product and see how and why people are interacting with it in the way they are. It gives us scope to improve the things that are working, and remove the barriers that aren't. I'm passionate about data-driven decisionmaking, and can use it to help you save money while generating better results."
      img = "maddyKing_1.jpg"
      alt = "Maddy King business insights for entrepreneurs"
      social = [
        ["icon-pin"],
        ["icon-graph"],
        ["icon-puzzle"]
      ]

    [[params.about.item]]
      name = "Technical skills"
      position = "Sometimes you need someone who speaks tech"
      description = "All businesses need to have an online presence, and this can be frustrating, daunting and expensive. As an experienced coder, I can take the pain out of this process, helping you make technical decisions in the best interests of your business, and getting the most out of your developers."
      img = "maddyKing_2.jpg"
      alt = "Digital project manager"
      social = [
        ["icon-link"],
        ["icon-speedometer"],
        ["icon-mouse"]
      ]      

# Work section
  [params.work]
    enable = true
    title = "Previous Work"
    description = "We supercharged these projects through a range of services"
    footertext = ''
    url = "#fh5co-contact"
    button = "Book now"

    [[params.work.row]]
      img = "clients/lalatat.svg"
      alt = "digital strategy"
      url= "https://lalatat.com"
      title = "LALATAT"
      subtitle = "Marketing Training"
      style = "object-fit: fill"

    [[params.work.row]]
      img = "clients/realness.png"
      alt = "small business consultant"
      url= "https://therealness.world"
      title = "The Realness"
      subtitle = "Product Management"

    [[params.work.row]]
      img = "clients/swayable.jpg"
      alt = "marketing consultant"
      url= "https://swayable.com"
      title = "Swayable"
      subtitle = "Web Development"

    [[params.work.row]]
      img = "clients/bamboocreative.svg"
      alt = "digital project manager"
      url= "https://bamboocreative.nz/"
      title = "Bamboo Creative"
      subtitle = "Web Development"
      style = "object-fit: contain"

    [[params.work.row]]
      img = "clients/don_eda.jpg"
      alt = "low cost social media marketing"
      url= "https://devacademy.co.nz/"
      title = "Enspiral Dev Academy"
      subtitle = "Marketing Management"

    [[params.work.row]]
      img = "clients/beyondviolence.jpg"
      alt = "campaign manager"
      url= "https://www.youtube.com/watch?v=HIwTJVXNOH4"
      title = "Beyond Violence"
      subtitle = "Project Management"
      style = "object-fit: contain"

# Casestudy section
  [params.casestudy]
    enable = false
    title = "Case Study"
    description = "Working with The Realness"
    icon= ""

    [params.casestudy.video]
      enable = true
      title = ""
      icon = "icon-energy"
      url = "https://www.youtube.com/watch?v=8HvPHo8Ldc0"
      subheading = "Working with The Realness" 


  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "clients/full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 20
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Cups of tea"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 4000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 9
      interval = 50
      speed = 4000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Let's get a coffee, discuss your challenges and see if I can help."
    
    # Available icons: https://simplelineicons.github.io/
    details = [
        ["icon-home", "Level 2, 40 Taranaki Street, Wellington"],
        ["icon-globe", "Success working with clients remotely"],
        ["icon-envelope", "me@maddyking44.com"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Configure map address in hugo-elate-theme/ static/ js/ leaflet-map.js var latLong

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Maddy King 2020'
    links = [
        ["icon-twitter", "http://www.twitter.com/maddyking44"],
        ["icon-facebook", "http://www.facebook.com/maddy.king.71"],
        ["icon-linkedin", "http://www.linkedin.com/in/madelineking44"]
      ]
